version: "3.9"

services:
  app:
    build:
      dockerfile: devops/build/Dockerfile
      context: "."
    image: alpaca00/dtapi
    env_file: .env
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 2024M
          cpus: '0.75'
    command: sh -c "cd '/app' && uvicorn wsgi:app --host 0.0.0.0 --port 5000"
  bot:
    build:
      dockerfile: devops/build/Dockerfile
      context: "."
    image: alpaca00/dtbot
    env_file: .env
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 2024M
          cpus: '1.75'
    command: sh -c "cd '/app' && python dt/telegram/main.py"
    depends_on:
      - app
#      - postgres
#      - mongo

#  postgres:
#    image: postgres:15-alpine
#    restart: always
#    env_file: .env
#    ports:
#      - "5432:5432"
#
#  mongo:
#    image: mongo:7.0.16-jammy
#    restart: always
#    env_file: .env
#    ports:
#      - "27017:27017"
